[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Form handling
[[forms]]
  name = "founders-signup"
  action = "/founders-club"

[[forms]]
  name = "contact"
  action = "/contact"

# Redirects
[[redirects]]
  from = "/founders"
  to = "/#founders-club"
  status = 301

[[redirects]]
  from = "/membership"
  to = "/#membership"
  status = 301